Traceback (most recent call last):
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
h = 6.626e-34
hbar = h/(2*np.pi)
me = 9.1093e-31 # kg
r0 = 10e-9
n2 = 2
n1 = 1
print(hbar**2/(2*me*r0**2)*6.022e23/1000*(spherical_jn_zero(1,1)**2-spherical_jn_zero(0,1)**2))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/td/dll8n_kj4vd0zxjm0xd9m7740000gq/T/ipykernel_73816/2252883425.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mn2[0m [0;34m=[0m [0;36m2[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mn1[0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mprint[0m[0;34m([0m[0mhbar[0m[0;34m**[0m[0;36m2[0m[0;34m/[0m[0;34m([0m[0;36m2[0m[0;34m*[0m[0mme[0m[0;34m*[0m[0mr0[0m[0;34m**[0m[0;36m2[0m[0;34m)[0m[0;34m*[0m[0;36m6.022e23[0m[0;34m/[0m[0;36m1000[0m[0;34m*[0m[0;34m([0m[0mspherical_jn_zero[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m**[0m[0;36m2[0m[0;34m-[0m[0mspherical_jn_zero[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m**[0m[0;36m2[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'spherical_jn_zero' is not defined
NameError: name 'spherical_jn_zero' is not defined

